--- conf/fluent-bit.conf.orig	2026-08-15 03:52:07 UTC
+++ conf/fluent-bit.conf
@@ -133,8 +133,8 @@
     # storage.backlog.mem_limit 5M
 
 [INPUT]
-    name cpu
-    tag  cpu.local
+    name dummy
+    tag  demo.local
 
     # Read interval (sec) Default: 1
     interval_sec 1
