--- conf/fluent-bit.conf.orig	2026-02-19 03:26:01 UTC
+++ conf/fluent-bit.conf
@@ -82,8 +82,8 @@
     # storage.backlog.mem_limit 5M
 
 [INPUT]
-    name cpu
-    tag  cpu.local
+    name dummy
+    tag  demo.local
 
     # Read interval (sec) Default: 1
     interval_sec 1
