# common between x86/x86-64/arm64
GALLIUM_DRIVERS+=	SOFTPIPE NOUVEAU SVGA VIRGL #ZINK

# LLVMPIPE is supported on arm64, but currently the specification
# defines it as x86-only.  Once ARM64 is support, update this.

GALLIUM_X86=		R300 CROCUS I915
GALLIUM_X86_LLVM=	R600 RADEONSI LLVMPIPE
GALLIUM_ARM64=		V3D VC4 FREEDRENO ETNAVIV TEGRA LIMA PANFROST
GALLIUM_ALL_LLVM=	IRIS