CPP=	clang-cpp
# pulled from FreeBSD's gnustep extension

#GNUSTEP_PREFIX?=		${LOCALBASE}/GNUstep
#GNUSTEP_SYSTEM_ROOT=		${GNUSTEP_PREFIX}/System
#GNUSTEP_MAKEFILES=		${GNUSTEP_SYSTEM_ROOT}/Library/Makefiles
#GNUSTEP_SYSTEM_LIBRARIES=	${GNUSTEP_SYSTEM_ROOT}/Library/Libraries
#GNUSTEP_SYSTEM_TOOLS=		${GNUSTEP_SYSTEM_ROOT}/Tools
#GNUSTEP_LOCAL_ROOT=		${GNUSTEP_PREFIX}/Local
#GNUSTEP_LOCAL_LIBRARIES=	${GNUSTEP_LOCAL_ROOT}/Library/Libraries
#GNUSTEP_LOCAL_TOOLS=		${GNUSTEP_LOCAL_ROOT}/Tools
#PREPEND_PATH=	${GNUSTEP_SYSTEM_TOOLS}:${GNUSTEP_LOCAL_TOOLS}

GNUSTEP_MAKEFILES=		${LOCALBASE}/share/GNUstep/Makefiles

MAKE_ENV+=	GNUSTEP_MAKEFILES="${GNUSTEP_MAKEFILES}"
CONFIGURE_ENV+=	GNUSTEP_MAKEFILES="${GNUSTEP_MAKEFILES}"
