--- sentinel.conf.orig	2026-05-05 13:23:21 UTC
+++ sentinel.conf
@@ -10,14 +10,14 @@ protected-mode no
 port 26379
 
 # By default Redis Sentinel does not run as a daemon. Use 'yes' if you need it.
-# Note that Redis will write a pid file in /var/run/redis-sentinel.pid when
+# Note that Redis will write a pid file in %%PREFIX%%/var/run/redis/redis-sentinel.pid when
 # daemonized.
 daemonize no
 
 # When running daemonized, Redis Sentinel writes a pid file in
-# /var/run/redis-sentinel.pid by default. You can specify a custom pid file
+# %%PREFIX%%/var/run/redis/redis-sentinel.pid by default. You can specify a custom pid file
 # location here.
-pidfile /var/run/redis-sentinel.pid
+pidfile %%PREFIX%%/var/run/redis/redis-sentinel.pid
 
 # Specify the server verbosity level.
 # This can be one of:
