--- Cargo.toml.orig	2026-06-17 13:03:47 UTC
+++ Cargo.toml
@@ -24,7 +24,7 @@ ferron-modules-builtin = { path = "./fer
 ferron-observability-builtin = { path = "./ferron-observability-builtin", default-features = false }
 
 [patch.crates-io]
-monoio = { git = "https://github.com/DorianNiemiecSVRJS/monoio.git" }                                           # This is needed for the web server to be able to accept more than one connection on Windows, and to be able to be compiled correctly on FreeBSD
+monoio = { path = "/construction/ferron/monoio-7955c1356585d7ebd45d67f5932620c09ac0a701/monoio" }
 
 [patch.'https://github.com/ferronweb/ferron']
 ferron-common = { path = "./ferron-common" }
