--- mkdocs.yml.orig	2026-06-02 14:11:34 UTC
+++ mkdocs.yml
@@ -1,6 +1,6 @@
 # Note: NetBox has migrated from MkDocs to Zensical
 site_name: NetBox Documentation
-site_dir: netbox/project-static/docs
+site_dir: project-static/docs
 site_url: https://docs.netbox.dev/
 repo_name: netbox-community/netbox
 repo_url: https://github.com/netbox-community/netbox
