--- cmake/install_layout.cmake.orig	2020-06-16 16:31:03 UTC
+++ cmake/install_layout.cmake
@@ -379,11 +379,7 @@ SET(ROUTER_INSTALL_LOGDIR_STANDALONE
 SET(ROUTER_INSTALL_RUNTIMEDIR_STANDALONE "run")
 
 SET(ROUTER_INSTALL_BINDIR_STANDALONE      "bin")
-IF(LINUX)
-  SET(ROUTER_INSTALL_LIBDIR_STANDALONE    "lib/mysqlrouter/private")
-ELSE()
   SET(ROUTER_INSTALL_LIBDIR_STANDALONE    "lib")
-ENDIF()
 IF(WIN32)
   SET(ROUTER_INSTALL_PLUGINDIR_STANDALONE "lib")
 ELSE()
