--- src/tools/gprconfig.adb.orig	2022-09-22 17:09:03 UTC
+++ src/tools/gprconfig.adb
@@ -571,7 +571,7 @@ procedure GPRconfig is
          Text_IO.Put_Line
            ("--------------------------------------------------");
          Text_IO.Put_Line
-           ("gprconfig has found the following compilers on your PATH.");
+           ("gpr2config has found the following compilers on your PATH.");
          Text_IO.Put_Line
            ("Only those matching the target and the selected compilers"
             & " are displayed.");
@@ -669,7 +669,7 @@ procedure GPRconfig is
       Text_IO.Put_Line
         ("You can regenerate the same config file in batch mode");
       Text_IO.Put_Line (" with the following command line:");
-      Text_IO.Put ("gprconfig --batch");
+      Text_IO.Put ("gpr2config --batch");
       Text_IO.Put (" --target=");
       Text_IO.Put (Target);
 
@@ -766,7 +766,7 @@ begin
            (Text_IO.Standard_Error,
             Ada.Exceptions.Exception_Message (E));
    end;
-   GPRtools.Util.Set_Program_Name ("gprconfig");
+   GPRtools.Util.Set_Program_Name ("gpr2config");
 
    Register_Cmd_Options;
 
@@ -996,7 +996,7 @@ begin
         (Output, Text_IO.Out_File, To_String (Output_File));
 
       Text_IO.Put_Line
-        (Output, "--  This gpr configuration file was generated by gprconfig");
+        (Output, "--  This gpr configuration file was generated by gpr2config");
       Text_IO.Put_Line (Output, "--  using this command line:");
       Text_IO.Put (Output, "--  " & Ada.Command_Line.Command_Name);
 
@@ -1029,7 +1029,7 @@ exception
          "Missing parameter for switch: -" & Full_Switch);
       Text_IO.Put_Line
         (Text_IO.Standard_Error,
-         "try ""gprconfig --help"" for more information.");
+         "try ""gpr2config --help"" for more information.");
 
    when E : others =>
       Text_IO.Put_Line
