--- lib/util/pkcs11n.h.orig	2025-06-19 13:14:58 UTC
+++ lib/util/pkcs11n.h
@@ -630,7 +630,7 @@ _NSS_DEPRECATE_DEFINE_TYPE(CK_TRUST, CKT
 #define CKT_NSS_VALID \
     _NSS_DEPRECATE_DEFINE_VALUE(CKT_NSS_VALID, CKT_NSS_NOT_TRUSTED)
 _NSS_DEPRECATE_DEFINE_TYPE(CK_TRUST, CKT_NSS_MUST_VERIFY,
-                           "CKT_NSS_MUST_VERIFY really functions as CKT_NSS_TRUST_UNKNOWN");
+                           "CKT_NSS_MUST_VERIFY really functions as CKT_NSS_TRUST_UNKNOWN")
 #define CKT_NSS_MUST_VERIFY \
     _NSS_DEPRECATE_DEFINE_VALUE(CKT_NSS_MUST_VERIFY, CKT_NSS_TRUST_UNKNOWN)
 
