--- cargo-crates/tokio-1.44.2/Cargo.toml.orig	2025-04-29 04:32:32 UTC
+++ cargo-crates/tokio-1.44.2/Cargo.toml
@@ -809,7 +809,7 @@ version = "0.5.5"
 [target.'cfg(not(target_family = "wasm"))'.dev-dependencies.tempfile]
 version = "3.1.0"
 
-[target.'cfg(target_os = "freebsd")'.dev-dependencies.mio-aio]
+[target.'cfg(any(target_os = "freebsd", target_os = "dragonfly"))'.dev-dependencies.mio-aio]
 version = "0.9.0"
 features = ["tokio"]
 
