--- cargo-crates/shadowsocks-service-1.23.2/Cargo.toml.orig	2025-04-29 04:32:32 UTC
+++ cargo-crates/shadowsocks-service-1.23.2/Cargo.toml
@@ -343,7 +343,7 @@ version = "1.5"
 [dev-dependencies.env_logger]
 version = "0.11"
 
-[target.'cfg(any(target_os = "macos", target_os = "ios", target_os = "freebsd", target_os = "openbsd"))'.dependencies.nix]
+[target.'cfg(any(target_os = "macos", target_os = "ios", target_os = "freebsd", target_os = "openbsd", target_os = "dragonfly"))'.dependencies.nix]
 version = "0.29"
 features = ["ioctl"]
 
