--- cargo-crates/tokio-1.45.0/Cargo.toml.orig	2025-05-12 00:10:42 UTC
+++ cargo-crates/tokio-1.45.0/Cargo.toml
@@ -804,7 +804,7 @@ version = "0.5.5"
 [target.'cfg(not(target_family = "wasm"))'.dev-dependencies.tempfile]
 version = "3.1.0"
 
-[target.'cfg(target_os = "freebsd")'.dev-dependencies.mio-aio]
+[target.'cfg(target_os = "freebsd", target_os = "dragonfly")'.dev-dependencies.mio-aio]
 version = "1"
 features = ["tokio"]
 
