
[net]
offline = true

[patch."https://github.com/astral-sh/ruff"]
ruff_python_ast = {path = "/construction/python-ast-serialize/ruff-0.15.5/crates/ruff_python_ast"}
ruff_python_parser = {path = "/construction/python-ast-serialize/ruff-0.15.5/crates/ruff_python_parser"}
ruff_python_trivia = {path = "/construction/python-ast-serialize/ruff-0.15.5/crates/ruff_python_trivia"}
ruff_source_file = {path = "/construction/python-ast-serialize/ruff-0.15.5/crates/ruff_source_file"}
ruff_text_size = {path = "/construction/python-ast-serialize/ruff-0.15.5/crates/ruff_text_size"}
