include/poppler/cpp/poppler-destination.h
include/poppler/cpp/poppler-document.h
include/poppler/cpp/poppler-embedded-file.h
include/poppler/cpp/poppler-font-private.h
include/poppler/cpp/poppler-font.h
include/poppler/cpp/poppler-global.h
include/poppler/cpp/poppler-image.h
include/poppler/cpp/poppler-page-renderer.h
include/poppler/cpp/poppler-page-transition.h
include/poppler/cpp/poppler-page.h
include/poppler/cpp/poppler-rectangle.h
include/poppler/cpp/poppler-toc.h
include/poppler/cpp/poppler-version.h
include/poppler/cpp/poppler_cpp_export.h
lib/libpoppler-cpp.so
lib/libpoppler-cpp.so.%%CPP_SOMAJOR%%
lib/libpoppler-cpp.so.%%CPP_SOVERSION%%
lib/pkgconfig/poppler-cpp.pc
