--- src/libs/libgroff/Makefile.sub.orig	2014-11-04 08:38:35 UTC
+++ src/libs/libgroff/Makefile.sub
@@ -176,7 +176,7 @@ ref-del.sed : $(srcdir)/ref-del.sin
 
 MKINSTALLDIRS = $(SHELL) $(top_srcdir)/mkinstalldirs
 
-install_data: install_charset_data
+install_data:
 install_charset_data:
 	-test $(GLIBC21) != no || $(MKINSTALLDIRS) $(DESTDIR)$(libdir)
 	if test -f $(DESTDIR)$(libdir)/charset.alias; then \
