--- pyproject.toml.orig	2026-07-31 22:06:51 UTC
+++ pyproject.toml
@@ -3,7 +3,6 @@ build-backend = "mesonpy"
 requires = [
   "meson>=1.11.2",
   "meson-python>=0.20",
-  "ninja>=1.13",
 ]
 
 [project]
