--- evdev/genecodes.py.orig	2023-01-20 15:35:36.000000000 +0100
+++ evdev/genecodes.py	2023-09-08 16:20:56.355314000 +0200
@@ -30,12 +30,8 @@
 #-----------------------------------------------------------------------------
 template = r'''
 #include <Python.h>
-#ifdef __FreeBSD__
-#include <dev/evdev/input.h>
-#else
 #include <linux/input.h>
 #include <linux/uinput.h>
-#endif
 
 /* Automatically generated by evdev.genecodes */
 /* Generated on %s */
