--- library/std/src/fs/tests.rs.orig	2026-08-18 19:58:58 UTC
+++ library/std/src/fs/tests.rs
@@ -180,6 +180,7 @@ fn file_test_io_seek_and_write() {
         target_os = "aix",
         target_os = "cygwin",
         target_os = "freebsd",
+        target_os = "dragonfly",
         target_os = "fuchsia",
         target_os = "hurd",
         target_os = "illumos",
@@ -214,6 +215,7 @@ fn file_lock_multiple_shared() {
         target_os = "aix",
         target_os = "cygwin",
         target_os = "freebsd",
+        target_os = "dragonfly",
         target_os = "fuchsia",
         target_os = "hurd",
         target_os = "illumos",
@@ -249,6 +251,7 @@ fn file_lock_blocking() {
         target_os = "aix",
         target_os = "cygwin",
         target_os = "freebsd",
+        target_os = "dragonfly",
         target_os = "fuchsia",
         target_os = "hurd",
         target_os = "illumos",
@@ -281,6 +284,7 @@ fn file_lock_drop() {
         target_os = "aix",
         target_os = "cygwin",
         target_os = "freebsd",
+        target_os = "dragonfly",
         target_os = "fuchsia",
         target_os = "hurd",
         target_os = "illumos",
@@ -315,6 +319,7 @@ fn file_lock_dup() {
         target_os = "aix",
         target_os = "cygwin",
         target_os = "freebsd",
+        target_os = "dragonfly",
         target_os = "fuchsia",
         target_os = "hurd",
         target_os = "illumos",
