# From gnat_util-gpl-2018-20180524, file: MANIFEST.gnat_util (sorted)
# minus *.gpr, sdefault_adb.gnat_util, 	gnat_util_dummies.c
GNAT_SRCS= \
	ali-util.adb \
	ali-util.ads \
	ali.adb \
	ali.ads \
	alloc.ads \
	aspects.adb \
	aspects.ads \
	atree.adb \
	atree.ads \
	binderr.adb \
	binderr.ads \
	butil.adb \
	butil.ads \
	casing.adb \
	casing.ads \
	csets.adb \
	csets.ads \
	debug.adb \
	debug.ads \
	einfo.adb \
	einfo.ads \
	elists.adb \
	elists.ads \
	err_vars.ads \
	errout.adb \
	errout.ads \
	erroutc.adb \
	erroutc.ads \
	errutil.adb \
	errutil.ads \
	fmap.adb \
	fmap.ads \
	fname-uf.adb \
	fname-uf.ads \
	fname.adb \
	fname.ads \
	get_scos.adb \
	get_scos.ads \
	gnatvsn.adb \
	gnatvsn.ads \
	hostparm.ads \
	krunch.adb \
	krunch.ads \
	lib-list.adb \
	lib-sort.adb \
	lib.adb \
	lib.ads \
	link.c \
	namet.adb \
	namet.ads \
	nlists.adb \
	nlists.ads \
	opt.adb \
	opt.ads \
	osint.adb \
	osint.ads \
	output.adb \
	output.ads \
	put_scos.adb \
	put_scos.ads \
	repinfo.adb \
	repinfo.ads \
	restrict.adb \
	restrict.ads \
	rident.ads \
	scans.adb \
	scans.ads \
	scng.adb \
	scng.ads \
	scos.adb \
	scos.ads \
	sdefault.ads \
	sem_aux.adb \
	sem_aux.ads \
	sinfo.adb \
	sinfo.ads \
	sinput-c.adb \
	sinput-c.ads \
	sinput.adb \
	sinput.ads \
	snames.adb-tmpl \
	snames.ads-tmpl \
	snames.h-tmpl \
	stand.adb \
	stand.ads \
	stringt.adb \
	stringt.ads \
	styleg.adb \
	styleg.ads \
	stylesw.adb \
	stylesw.ads \
	switch-m.adb \
	switch-m.ads \
	switch.adb \
	switch.ads \
	table.adb \
	table.ads \
	targparm.adb \
	targparm.ads \
	tempdir.adb \
	tempdir.ads \
	tree_in.adb \
	tree_in.ads \
	tree_io.adb \
	tree_io.ads \
	types.adb \
	types.ads \
	uintp.adb \
	uintp.ads \
	uname.adb \
	uname.ads \
	urealp.adb \
	urealp.ads \
	widechar.adb \
	widechar.ads \
	xsnamest.adb \
	xutil.adb \
	xutil.ads
