--- cargo-crates/shadowsocks-service-1.23.3/Cargo.toml.orig	2025-05-12 00:10:42 UTC
+++ cargo-crates/shadowsocks-service-1.23.3/Cargo.toml
@@ -343,7 +343,7 @@ version = "0.7"
 features = ["async"]
 optional = true
 
-[target.'cfg(any(target_os = "macos", target_os = "ios", target_os = "freebsd", target_os = "openbsd"))'.dependencies.nix]
+[target.'cfg(any(target_os = "macos", target_os = "ios", target_os = "freebsd", target_os = "openbsd", target_os = "dragonfly"))'.dependencies.nix]
 version = "0.30"
 features = ["ioctl"]
 
