--- cargo-crates/tun-0.7.19/Cargo.toml.orig	2025-05-12 00:10:42 UTC
+++ cargo-crates/tun-0.7.19/Cargo.toml
@@ -142,7 +142,7 @@ version = "1"
 version = "1"
 features = ["rt-multi-thread"]
 
-[target.'cfg(any(target_os = "macos", target_os = "freebsd"))'.dependencies.ipnet]
+[target.'cfg(any(target_os = "macos", target_os = "freebsd", target_os = "dragonfly"))'.dependencies.ipnet]
 version = "2"
 
 [target.'cfg(target_os = "windows")'.dependencies.futures]
