REPLACE_LIST= \
	external/curl/ExternalProject_curl.mk \
	external/liblangtag/ExternalProject_liblangtag.mk \
	external/libxslt/ExternalProject_libxslt.mk \
	external/nss/ExternalProject_nss.mk \
	external/openssl/ExternalProject_openssl.mk \
	external/redland/ExternalProject_raptor.mk \
	external/redland/ExternalProject_rasqal.mk \
	external/redland/ExternalProject_redland.mk \
	external/xmlsec/ExternalProject_xmlsec.mk \
	include/osl/endian.h \
	sal/osl/unx/system.cxx \
	solenv/bin/modules/installer/parameter.pm \
	soltools/mkdepend/main.c \
	stoc/source/corereflection/criface.cxx \
	vcl/qa/cppunit/BitmapTest.cxx \
	vcl/unx/generic/app/saldata.cxx \
	vcl/unx/generic/dtrans/X11_selection.cxx \
	vcl/unx/generic/gdi/salbmp.cxx \
	vcl/unx/generic/printer/printerinfomanager.cxx \
	desktop/unx/source/start.c \
	sal/osl/unx/process_impl.cxx \
	sal/osl/unx/sockimpl.hxx \
	sal/osl/unx/pipe.cxx \
	vcl/unx/gtk3/gtk3gtkdata.cxx \
	# end-list

PERCENT_BSD_LIST= \
	Repository.mk \
	canvas/Executable_canvasdemo.mk \
	chart2/Library_chartcore.mk \
	desktop/CppunitTest_desktop_app.mk \
	desktop/Library_crashreport.mk\
	desktop/Library_sofficeapp.mk \
	libreofficekit/Module_libreofficekit.mk \
	libreofficekit/Executable_gtktiledviewer.mk \
	libreofficekit/Library_libreofficekitgtk.mk \
	sc/CppunitTest_sc_ucalc.mk \
	sc/Library_sc.mk \
	svl/Library_svl.mk \
	svx/Executable_gengal.mk \
	vcl/Executable_vcldemo.mk \
	vcl/Executable_visualbackendtest.mk \
	vcl/Executable_ui-previewer.mk \
	vcl/Executable_mtfdemo.mk \
	vcl/Module_vcl.mk \
	vcl/Library_desktop_detector.mk \
	vcl/Library_vcl.mk \
	vcl/Executable_icontest.mk

