REPLACE_LIST= \
	bridges/Library_cpp_uno.mk \
	external/xmlsec/ExternalProject_xmlsec.mk \
	external/redland/ExternalProject_redland.mk \
	external/redland/ExternalProject_rasqal.mk \
	external/redland/ExternalProject_raptor.mk \
	external/python3/UnpackedTarball_python3.mk \
	external/openssl/ExternalProject_openssl.mk \
	external/nss/ExternalProject_nss.mk \
	external/libxslt/ExternalProject_libxslt.mk \
	external/liblangtag/ExternalProject_liblangtag.mk \
	external/curl/ExternalProject_curl.mk \
	jvmfwk/Package_rcfiles.mk \
	odk/settings/settings.mk \
	odk/Executable_unoapploader.mk \
	odk/CustomTarget_check.mk \
	pyuno/Library_pyuno_wrapper.mk \
	sd/Module_sd.mk \
	shell/Module_shell.mk \
	sal/osl/unx/process_impl.cxx \
	sal/osl/unx/pipe.cxx \
	vcl/unx/gtk3/gtkdata.cxx \
	vcl/unx/generic/printer/printerinfomanager.cxx \
	vcl/unx/generic/app/saldata.cxx \
	vcl/qa/cppunit/BitmapTest.cxx \
	include/osl/endian.h \
	soltools/mkdepend/main.c \
	desktop/unx/source/start.c
	# end-list

PERCENT_BSD_LIST= \
	Repository.mk \
	desktop/Library_crashreport.mk \
	libreofficekit/Executable_gtktiledviewer.mk \
	libreofficekit/Library_libreofficekitgtk.mk \
	libreofficekit/Module_libreofficekit.mk \
	svl/Library_svl.mk \
	vcl/Library_vcl.mk \
	vcl/Module_vcl.mk \
	# end-list

